### ISSUE TITLE
Completions for all man pages

### ISSUE THREAD

**Issue by fr3du** [qbit/ohmyksh#1]
Hello,

Would something like this be worth implementing to get completions for all manual pages? 

https://gist.github.com/fr3du/9ceddfeff3ed9be34542c812e9de33f7

**Comment by bijanebrahimi** [comment]
@fr3du Hi,

I have a similar diff but a little more cleaner (I guess). I already sent a pull request (#3) which is waiting for approval. Hope it helps.

Cheers

**Comment by qbit** [comment]
Sorry about not noticing this! I turned notifications to "only mentions" somehow :P

#3 has been merged!

**Comment by qbit** [comment]
Also, forgot to mention earlier - I switched the primary branch to main. So if you aren't seeing recent changes in your checkout, that's why.

**Comment by rjc** [comment]
Just an FIY to those who are interested, I just sent a PR (#7) with an improved `man(1)` completion.
